### PR TITLE
Site revisions

### PR DESCRIPTION
**Pull request by jcstein**
- [x] review structure of rollkit stack page
- [x] Add "our goal is to make" to "it as easy to deploy a rollup as it is to deploy a smart contract ee29688dad821a0bc45f19f02174f3b12d2a0589
- [x] expand tutorials category 1df200ee12eb655a6621233d7546e4aa9d0585e7
- [x] "Freedom to configure the execution environment" This isn't sovereignty but moreso customizability / flexibility 92fc6909b128ad56e0bccd9fcc53ea693fa3377d
- [x] "Rollkit can also be used to deploy rollups on existing settlement and execution layers" it can't currently do this 2738aa994f2452dbae4a86efbe064783364376a9
- [x] "Rollkit is built as an open-source framework, so that developers could easily import existing modules into their applications. We encourage developers to contribute to the development of Rollkit modules by adding new ones or improving existing ones." usage of the word "modules" has baggage from Cosmos-SDK, I'd say replace it with "Rollkit is built as an open-source framework, so that developers could easily modify it to suit their applications" 42b1bbafe3644d50f9b37920806ae2934a9ab6a8
- [x] add "intro" to top bar navigation a6467d3524091d9f3fca517778bd7dd539c879bd
- [x] clarify centralized sequencer in table 1a40568f7a544a49005072ee1d9eb90e0980e1a8
- [x] data availability is duplicated across two sections in the rollkit stack page - delete first DA and move Celestia to second
- [x] add new logo
- [x] add new OG image
- [x] add sentence case

### CODE REVIEW

**Comment by musalbas** [comment]
Made some improvements on the homepage

@jcstein can you change the emoji for flexible to something more relevant like https://emojipedia.org/gear/?

**Comment by jcstein** [comment]
Yes @musalbas - I'm using twitter emojis because they're OS and free for now. will swap

**Comment by jcstein** [comment]
Which do you lean towards us using?

**Comment by AlCJoseph** [comment]
Rollkit name disappear . there's only the logo

**Review by nashqueue — APPROVED** [review]

**Pull request merged**
