### PR TITLE
feat: new vitepress site

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Preview at https://jcstein.github.io/rollkit-vitepress/
resolves https://github.com/rollkit/docs/issues/196
resolves https://github.com/rollkit/docs/issues/48

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
oh it's because the old workflows are being run, not current (i think)

**Comment by jcstein** [comment]
swapped to yarn and tested on my version successfully: https://github.com/jcstein/rollkit-vitepress/actions/runs/5714578601

**Comment by jcstein** [comment]
- [ ] look into .vitepress cache files and remove if not necessary

**Comment by Manav-Aggarwal** [comment]
Thanks for working on this! Looks great so far. 

Some initial comments:

- Under the `Why Rollkit?` section under `Customizability`, maybe we can emphasize on the four main components we aim to customize - Execution Environments, Data Availability layers, Proof System, and Sequencer Schemes. 

- Under the `Rollkit Stack` section, we mention the following paragraph:

> And don't forget to replace another dependency, tendermint, with [rollkit/tendermint](https://github.com/rollkit/tendermint), which has an enhanced ABCI interface that includes the methods needed for state fraud proofs. 

This was removed recently from `main`, can we please update this with a `cometbft` version that works with us? This requires a new release. cc: @gupadhyaya 

- In the same section under `Data Availability`, we mention the following paragraph:

> The DataAvailabilityLayerClient interface includes essential lifecycle methods (Init, Start, Stop) as well as data availability methods (SubmitBlock, CheckBlockAvailability).

We recently got rid of the `CheckBlockAvailability` method from the interface and updated `SubmitBlock` to `SubmitBlocks`. Suggestion to update paragraph to:

> The DataAvailabilityLayerClient interface includes essential lifecycle methods (Init, Start, Stop) as well as data availability methods (SubmitBlocks, RetrieveBlocks).

- In the same section we describe how the DA implementation for `Celestia` works. We recently updated Rollkit to use `celestia-openrpc` instead of `go-cnc` so reflecting those changes here would make sense. Also, mentioning other existing DA implementations like Bitcoin, Mock, gRPC could make sense here too.

 - Comment out the following paragraph for now since we've removed State Fraud Proofs from the main for now.

> Receive state fraud proofs: state fraud proofs are received through a channel FraudProofInCh and Rollkit nodes attempt to verify them. Note that we plan to make this configurable for full nodes since full nodes also produce state fraud proofs on their own.

We can uncomment/add it back once we are ready to add State Fraud Proofs back.

- Perhaps we should modify references to `Tendermint` to `CometBFT` instead now that Rollkit uses `CometBFT`. 

- The link to the Fraud Proofs ADR under `Optimistic Rollups` is currently broken and can be updated to point to this [link](https://github.com/rollkit/rollkit/blob/main/docs/lazy-adr/adr-009-state-fraud-proofs.md) instead.

- Under the `Building with Rollkit` section, we should update the `rollkit` and `cometbft` versions to new releases without State Fraud Proofs.

I'll also go through all the tutorials and follow up with any additional comments.

**Comment by jcstein** [comment]
thanks for the feedback @Manav-Aggarwal !

>And don't forget to replace another dependency, tendermint, with [rollkit/tendermint](https://github.com/rollkit/tendermint), which has an enhanced ABCI interface that includes the methods needed for state fraud proofs.

This was removed recently from main, can we please update this with a cometbft version that works with us? This requires a new release. cc: @gupadhyaya
> 

- I implemented all changes except for the above. I think that we can merge docs and update this later, as the docs in this PR are mirroring the current site. note: since the tutorials still use tendermint, i did not modify the tutorials and have opened a new issue for this in #199 

> Also, mentioning other existing DA implementations like Bitcoin, Mock, gRPC could make sense here too.
- added this as plain text with no links for now. what's the best place to link to these examples?

> Under the Building with Rollkit section, we should update the rollkit and cometbft versions to new releases without State Fraud Proofs.
- what are these versions? I think this corresponds with #199 

is any of this blocking merging docs and then making the changes in this comment after?

**Review by Manav-Aggarwal — APPROVED** [review]

**Review by nashqueue — APPROVED** [review]

**Comment by nashqueue** [comment]
Thank you Josh , I agree that we should merge the migrations and make any adjustments after to not block this.

**Comment by Manav-Aggarwal** [comment]
I think the issue you linked should cover everything, thanks! Approved.

**Pull request merged**
