### PR TITLE
chore: add README and import script

### LINKED ISSUE #193: import README to docs for "building with rollkit" page

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Resolves #193 

This removes the [building-with-rollkit page](https://rollkit.dev/learn/building-with-rollkit) and uses the [README from rollkit/rollkit](https://github.com/rollkit/rollkit#readme) using an `importReadme.mjs` script.

This is so that we can import with a script similarly to the way that [this script](https://github.com/celestiaorg/docs/blob/main/importMarkdown.mjs) pulls in Blobstream (fka QGB) docs in.

This PR is to be updated and merged after [this 1247 on rollkit](https://github.com/rollkit/rollkit/pull/1247)

[Preview of page in this PR](https://rollkit.dev/pr-preview/pr-261/learn/readme)

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by MSevey** [comment]
Does this render updates automatically? 

If so, do we have any concerns with it targeting main vs a release?

If it targets a release, we could look into setting a trigger to auto update this like the other versions in the docs.

**Comment by jcstein** [comment]
the script can currelty be run manually. so the current idea would be to run this after a release of rollkit, and make a PR with the edited file. just run `yarn import-readme`, then push, & make PR

however, i think targeting a release, turning this into a github action instead of just a script, and implementing latest tags workflow in vitepress is better in the long run

**Comment by jcstein** [comment]
are you alright with merging this and in a following PR completing:
- [ ] target a release instead of main, combining with #185 
- [ ] turn this into a workflow

**Review by nashqueue — APPROVED** [review]
Thank you

**Pull request merged**
