### PR TITLE
feat: Add centralized sequencer to genesis in all tutorials

### PR DESCRIPTION
**Pull request by Manav-Aggarwal**
## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

## Summary by CodeRabbit

- **New Features**
  - Integrated centralized sequencer address and public key into the genesis configuration for enhanced network setup.
  - Implemented authorization token generation for light clients to improve security and access control.

- **Documentation**
  - Updated dependency versions in tutorial documentation to align with the latest software releases.

- **Chores**
  - Performed updates to ensure project dependencies are synchronized and compatible with the current environment.

### CODE REVIEW

**Comment by gupadhyaya** [comment]
@Manav-Aggarwal can you also update polaris?

**Comment by jcstein** [comment]
https://github.com/rollkit/docs/pull/269/commits/77a4ea54f27244d17671c166678183f8bb5f248c - this should resolve conflicts with restart script that you added @Manav-Aggarwal, but is untested

**Comment by jcstein** [comment]
> @Manav-Aggarwal can you also update polaris?

when we get to it we'll actually need to update polaris, other tutorials will be updated in this PR

**Review by jcstein — APPROVED** [review]
utACK

**Comment by jcstein** [comment]
i realized we'll need to update the versions used in the tutorials too

**Comment by jcstein** [comment]
[polaris is done here, everything else up to date in this pr](https://github.com/berachain/polaris/commit/819af20e907bf3a0c21acdca3b1357831de7152e)

**Comment by jcstein** [comment]
i think the only thing missing here would be to:

- [ ] update the rollkit/rollkit readme to show the most up-to-date versions
- [ ] pull that in here with the `yarn import-readme` script
- [ ] merge this pr

**Comment by jcstein** [comment]
reported from community and also experienced myself

when using new versions, 2 things happen:

(1) `"must have exactly 1 validator (the centralized sequencer)"` error occurs when not using correct setup in start script
(2) if following instructions on this PR, or using a new version of Polaris, then there is a new error: `panic: genesisValidators[0] != req.Validators[0]`

**Comment by jcstein** [comment]
i think this still had some issues in comment above

**Pull request merged**
