### PR TITLE
Use rollkit v0.6.0 in tutorials

### PR DESCRIPTION
**Pull request by tzdybal**
Closes https://github.com/rollkit/docs/issues/43

### CODE REVIEW

**Review by jcstein — APPROVED** [review]
LGTM, after we merge Ethermint and update Ethermint in this tutorial

**Comment by jcstein** [comment]
not sure why Lint test is failing when those lines don't exist on this branch 🤔

**Review by gupadhyaya — APPROVED** [review]
LGTM

**Comment by jcstein** [comment]
Should we add ethermint in this PR @tzdybal?

**Pull request merged**
