### PR TITLE
add Polaris EVM to docs

### LINKED ISSUE #130: Make a tutorial for gmportal.xyz

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

[PREVIEW OF TUTORIAL
](https://rollkit.github.io/docs/pr-preview/pr-210/tutorials/polaris-evm)

This PR adds polaris.berachain.dev to the documentation for Rollkit.

- [x] double check golang version 
- [x] add links to polaris and berachain and more context 
- [x] add gm (ooga booga) portal, resolves #130 
- [ ] review from @berachain
- [x] add light node portion
- [ ] add guide on using light node instead

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
[Preview of Tutorial](https://rollkit.dev/pr-preview/pr-210/tutorials/polaris-evm)

**Comment by jcstein** [comment]
[Error](https://app.warp.dev/block/Mh3u983jjPyFLTPaR4Hv0U) when using https://github.com/rollkit/cosmos-sdk/releases/tag/v0.50.0-rc.0-rollkit-v0.11.0-rc0-no-fraud-proofs instead of https://github.com/rollkit/cosmos-sdk/releases/tag/v0.50.0-rc.0-rollkit-v0.11.0-rc0-no-fraud-proofs-test

**Comment by jcstein** [comment]
wild actually, when running on the version described in this tutorial, it crashed with the same [error](https://app.warp.dev/block/HWErAZSXKq8NnJsk4CFv6P) after 2000+ blocks?

**Review by nashqueue — COMMENTED** [review]
LGTM

**Comment by jcstein** [comment]
# To do

- [ ] update branches `rollkit` and `rollkit_v0.11.0-rc13-celestia-node` (for v0.11.0-rc13, maybe rename the branch, or create a new one based off of this)
- [ ] these versions, or version, should be compatible with both the latest [local-celestia-devnet](https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.11.0) and [celestia-node](https://github.com/celestiaorg/celestia-node/releases)
- [ ] update tutorial

**Review by nashqueue — APPROVED** [review]

**Pull request merged**
