### PR TITLE
Add State Fraud Proof docs

### PR DESCRIPTION
**Pull request by Manav-Aggarwal**
Closes: #64

### CODE REVIEW

**Comment by jcstein** [comment]
should we note that we don't currently have light nodes for Rollkit? and maybe that "multiple full nodes" is technically optional?

**Review by jcstein — COMMENTED** [review]
left a comment above, otherwise LGTM

**Comment by Manav-Aggarwal** [comment]
> thanks for the PR. i left some minor formatting edits and for linting. should we note that we don't currently have light nodes for Rollkit? and maybe that "multiple full nodes" is technically optional?

Thanks! Addressed the comment in the latest edit.

**Review by jcstein — APPROVED** [review]
You're welcome :shipit: left small change and LGTM

**Pull request merged**
