### PR TITLE
deps: change link to local devnet

### LINKED ISSUE #161: Update location of local-celestia-devnet image
self-explanatory with regards to this : https://rollkit.dev/docs/tutorials/gm-world/#-running-local-devnet-with-a-rollkit-rollup

### PR DESCRIPTION
**Pull request by jcstein**
Resolves #161 

This will be turned into a PR from a draft once there is an image built on `rollkit/local-celestia-devnet`.

### CODE REVIEW

**Comment by jcstein** [comment]
I'm waiting to merge this until the version is created, then will update the guide here

**Comment by jcstein** [comment]
https://rollkit.dev/pr-preview/pr-162/docs/tutorials/gm-world/#-running-local-devnet-with-a-rollkit-rollup

**Comment by jcstein** [comment]
https://rollkit.dev/pr-preview/pr-162/docs/tutorials/gm-world/#-running-local-devnet-with-a-rollkit-rollup

**Review by nashqueue — APPROVED** [review]
LGTM

**Pull request merged**
